### ISSUE TITLE
add script/notebook for generating test datasets

### ISSUE THREAD

**Issue by jhamman** [carbonplan/maps#11]
@freeman-lab - I believe you developed a Jupyter notebook for generating the test datasets used in the demo application. We should clean that up and add it to this repo.

**Comment by freeman-lab** [comment]
Yep I have it! Can keep as a notebook, or make a tiny script, but should it maybe live in `[ndpyramid](https://github.com/carbonplan/ndpyramid)` and we'll point to that in the demo's readme here? Feels a little cleaner to have the python all in one place.

**Comment by jhamman** [comment]
closed by https://github.com/carbonplan/ndpyramid/commit/736f04e5b0ec58ac4cbf1dd8290ac94cbd75cf69
