### ISSUE TITLE
Adding a `<Point />` component

### ISSUE THREAD

**Issue by Jakidxav** [carbonplan/maps#119]
I noticed that there is a `<Fill />` and `<Line />` component, but not one for points. From looking at other CarbonPlan repositories, it looks like most point layers are being added into the `map.style` object on map load. Is there any interest in a standalone `<Point />` component?

For what this could look like, I have an initial version [here](https://github.com/Jakidxav/maps/blob/main/src/point.js). A couple of notes about this component:
- It requires that the main map component has `glyphs` defined (i.e., `<Map ... glyphs={glyphs} />`, where for example `glyphs = 'http://fonts.openmaptiles.org/{fontstack}/{range}.pbf'`).
- I have initially combined the ability to add points and text labels into a single component. However, I could separate out the text labels (for example, into a `<Labels />` component) if that would be better.

**Comment by Shane98c** [comment]
This is a cool idea but we're inclined to keep the tool as theme-agnostic as possible (no predefined fonts etc.). You should be able to implement what you've done here in your app by using the `useMapbox` hook.
