### ISSUE TITLE
selections over chunks for large non-spatial dimensions

### ISSUE THREAD

**Issue by freeman-lab** [carbonplan/maps#25]
Wanted to share a summary of an offline discussion with @katamartin about rendering data where the non-spatial dimensions (e.g. time, band, etc.) are much larger than what we deal with now.

Currently, we have a hard-coded assumption that the non-spatial dimensions of data are stored in a single chunk. For example, if we have 10 time points and 2 bands and 128 pixel tiles, we assume that each chunk is (10 x 2 x 128 x 128). 

While this likely works so long as the non-spatial dimensions total < 50, we cannot reasonably handle a dataset with, say, 5000 time points and 10 bands, for two primary reasons:
- the likely noticeable delay loading such large chunks
- limits of storing such large chunks in memory

While our exact size limits are unclear without further testing, we should begin building in support for these larger data sets.

We agreed that the first step is to support working with datasets with **more than one chunk** along some/all of the non-spatial dimensions. For example, if a dataset with 5000 time points and 10 bands and 128 pixel tiles has a chunk size of (50 x 2 x 128 x 128), we should support rendering this data as a `<Raster/>` without any changes to our current consumer API.

Under the hood, this requires a couple key steps
1) on loading the pyramid, we need to track both the chunk size and the total array size
2) we need to use the provided `selector` prop to determine which chunk contains the requested data
3) we need to load and index into the appropriate chunk

Currently in step (2) we assume that the chunk is `0.0.x.y` where `x` and `y` are based on camera position (see [here](https://github.com/carbonplan/maps/blob/main/src/tiles.js#L298-L300)). That is the step that needs to be generalized.

A couple open questions that we can likely resolve once we begin implementing include:

- How to handle caching? Do we just cache one chunk at a time, or do we cache all chunks? There may be memory constraints and garbage collection concerns here.

- How to debounce? For spatial chunking, common interaction patterns (e.g. zooming, panning) effectively limit the rate of requests — though debouncing could still provide some benefits. With a slider that indexes into a 50000 length dimension, a single sweep of the slider without debouncing could trigger 1000s of chunk requests. We should probably support debouncing within the core library, and perhaps solve this simultaneously for both spatial and non-spatial dimensions.

- How to handle in `queryRegion`? Currently we return the entire chunk in a call to `queryRegion`, and the `selector` is ignored. We should probably instead pass the `selector` to `queryRegion` and only return the chunk that includes that selection. For the case of a single chunk, the behavior should be the same as it is now. We could possibly include an option to force retrieving all non-spatial chunks for the given region, though for some datasets this could create significant performance bottlenecks.

Finally, in specific use cases, there may be reasons to explore "pyramid" like data structures in non-spatial dimensions. For example, for long time series data (daily data over 150 years), one could precompute versions of the data aggregated to different time scales: e.g. daily (chunked by month), monthly (chunked by year), and annual (chunked by decade). Our current thinking is that, rather than build in non-spatial pyramid support within the core library, this should be done by specifying multiple `<Raster/>` components, for example

```
<Raster source='daily.zarr'/>
<Raster source='monthly.zarr'/>
<Raster source='annual.zarr'/>
```

Where only one at a time would be displayed depending on e.g. a UI selection. Given the wide variety of ways one might want to implement non-spatial pyramids, this approach gives maximal flexibility, especially while we better understand the use cases.

Importantly, solving the problem we focused on in this issue (selecting into multiple chunks) is a precursor to handling non-spatial pyramids of any kind, because at the highest-resolution of such a pyramid we always need to handle selecting and loading across multiple chunks.

**Comment by freeman-lab** [comment]
@katamartin for initial testing, there's now a dataset at `gs://carbonplan-share/maps-demo/3d/tavg-month-chunked` that's similar to the 3d test data we've been using with multiple months, except that instead of all 12 months in one chunk, there are two chunks of 6 months. 

To be super concrete, at level 1, the chunks are

```
0.0.0 (first 6 months, spatial chunk 0,0)
1.0.0 (second 6 months, spatial chunk 0,0)
0.0.1 (first 6 months, spatial chunk 0,1)
etc.
```

**Comment by katamartin** [comment]
Closing this as this was made possible in v2 (specifically in https://github.com/carbonplan/maps/pull/28)!

I'm thinking we can track any specific performance improvements in new issues.
